# Valkey replication group: single node group, encryption at rest and in
# transit, auth token, optional multi-AZ with automatic failover.
#
# Not a substitute for Next's MemoryDB cluster (ioredis.Cluster + ACL user
# impel-next). Gateway and identity use this module; Next uses modules/memorydb.

locals {
  # Family is the major version with no dot: 8.0 -> valkey8.
  parameter_group_family = "valkey${split(".", var.engine_version)[0]}"
  node_count             = 1 + var.replica_count
}

resource "aws_kms_key" "this" {
  #checkov:skip=CKV2_AWS_64:The default key policy grants the account root, which is what lets IAM policies govern access. A bespoke policy would have to re-grant ElastiCache and Secrets Manager by hand.
  description             = "Encryption at rest for the ${var.name} Valkey replication group."
  enable_key_rotation     = true
  deletion_window_in_days = 30

  tags = {
    Name = var.name
  }
}

resource "aws_kms_alias" "this" {
  name          = "alias/${var.name}"
  target_key_id = aws_kms_key.this.key_id
}

resource "aws_elasticache_subnet_group" "this" {
  name       = var.name
  subnet_ids = var.subnet_ids

  tags = {
    Name = var.name
  }
}

resource "aws_security_group" "this" {
  name        = "${var.name}-cache"
  description = "Valkey ${var.name} accepts encrypted traffic only from explicit client security groups."
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.name}-cache"
  }
}

resource "aws_vpc_security_group_ingress_rule" "valkey" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id = aws_security_group.this.id
  description       = "Valkey from ${each.value}."

  referenced_security_group_id = each.value
  from_port                    = 6379
  to_port                      = 6379
  ip_protocol                  = "tcp"
}

resource "aws_elasticache_parameter_group" "this" {
  name        = var.name
  family      = local.parameter_group_family
  description = "Parameters for ${var.name}."

  dynamic "parameter" {
    for_each = var.parameters

    content {
      name  = parameter.key
      value = parameter.value
    }
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ElastiCache has no equivalent to RDS manage_master_user_password, so the
# token is generated here and does land in state. Rotating means tainting this
# resource and restarting the consuming services.
resource "random_password" "auth_token" {
  length = 64
  # ElastiCache rejects several punctuation classes in auth tokens.
  special = false
}

resource "aws_secretsmanager_secret" "auth_token" {
  #checkov:skip=CKV2_AWS_57:The token is generated by Terraform; rotation is a taint of random_password plus a service restart, not a Lambda.
  name                    = "${var.name}/auth-token"
  description             = "Valkey auth token for ${var.name}."
  kms_key_id              = aws_kms_key.this.arn
  recovery_window_in_days = 0

  tags = {
    Name = "${var.name}-auth-token"
  }
}

resource "aws_secretsmanager_secret_version" "auth_token" {
  secret_id     = aws_secretsmanager_secret.auth_token.id
  secret_string = jsonencode({ auth_token = random_password.auth_token.result })
}

resource "aws_elasticache_replication_group" "this" {
  #checkov:skip=CKV2_AWS_50:Multi-AZ failover is var.multi_az, true by default. Dev runs single-node, where a failover target would double the cost of a disposable cache.
  replication_group_id = var.name
  description          = var.description

  engine         = "valkey"
  engine_version = var.engine_version
  node_type      = var.node_type
  port           = 6379

  # Cluster mode off: clients use one primary endpoint, no slot awareness.
  num_cache_clusters = local.node_count

  subnet_group_name    = aws_elasticache_subnet_group.this.name
  security_group_ids   = [aws_security_group.this.id]
  parameter_group_name = aws_elasticache_parameter_group.this.name

  multi_az_enabled           = var.multi_az
  automatic_failover_enabled = var.multi_az

  at_rest_encryption_enabled = true
  kms_key_id                 = aws_kms_key.this.arn
  transit_encryption_enabled = true
  auth_token                 = random_password.auth_token.result

  snapshot_retention_limit = var.snapshot_retention_days
  maintenance_window       = "sun:18:00-sun:19:00" # 02:00-03:00 SGT
  apply_immediately        = var.apply_immediately

  auto_minor_version_upgrade = true

  tags = {
    Name = var.name
  }

  lifecycle {
    precondition {
      condition     = !var.multi_az || var.replica_count >= 1
      error_message = "multi_az requires replica_count of at least 1: automatic failover needs somewhere to fail over to."
    }
  }
}
