# MemoryDB Redis cluster with TLS and a named ACL user. This is the Next
# cache contract (ioredis.Cluster + username impel-next). ElastiCache Valkey
# cluster-mode-off is not a substitute: the client discovers slots and
# authenticates as that ACL user, not a default AUTH token.

resource "aws_kms_key" "this" {
  #checkov:skip=CKV2_AWS_64:The default key policy grants the account root, which is what lets IAM policies govern access. A bespoke policy would have to re-grant MemoryDB and Secrets Manager by hand.
  description             = "Encryption at rest for the ${var.name} MemoryDB cluster."
  enable_key_rotation     = true
  deletion_window_in_days = 30

  tags = {
    Name = var.name
  }
}

resource "aws_kms_alias" "this" {
  name          = "alias/${var.name}"
  target_key_id = aws_kms_key.this.key_id
}

resource "aws_memorydb_subnet_group" "this" {
  name        = var.name
  description = "Private multi-AZ subnets for ${var.name}."
  subnet_ids  = var.subnet_ids

  tags = {
    Name = var.name
  }
}

resource "aws_security_group" "this" {
  #checkov:skip=CKV2_AWS_5:Attached via aws_memorydb_cluster.security_group_ids. Checkov does not follow that resource type.
  name        = "${var.name}-cache"
  description = "MemoryDB ${var.name} accepts encrypted traffic only from explicit client security groups."
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.name}-cache"
  }
}

resource "aws_vpc_security_group_ingress_rule" "redis" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id = aws_security_group.this.id
  description       = "MemoryDB from ${each.value}."

  referenced_security_group_id = each.value
  from_port                    = 6379
  to_port                      = 6379
  ip_protocol                  = "tcp"
}

# MemoryDB has no equivalent to RDS manage_master_user_password, so the
# password is generated here and does land in state. Rotating means tainting
# this resource, updating the user, and restarting the consuming services.
resource "random_password" "this" {
  length = 64
  # MemoryDB (and the prod CDK generateSecretString) reject punctuation.
  special = false
}

resource "aws_secretsmanager_secret" "password" {
  #checkov:skip=CKV2_AWS_57:The password is generated by Terraform; rotation is a taint of random_password plus a service restart, not a Lambda.
  name                    = "${var.name}/redis"
  description             = "Password for MemoryDB user ${var.user_name} on ${var.name}."
  kms_key_id              = aws_kms_key.this.arn
  recovery_window_in_days = 0

  tags = {
    Name = "${var.name}-redis"
  }
}

# Plain string, not JSON. Next's task injects the whole secret as
# IMPEL_REDIS_PASSWORD (prod CDK uses generateSecretString the same way).
resource "aws_secretsmanager_secret_version" "password" {
  secret_id     = aws_secretsmanager_secret.password.id
  secret_string = random_password.this.result
}

resource "aws_memorydb_user" "this" {
  user_name     = var.user_name
  access_string = "on ~* &* +@all"

  authentication_mode {
    type      = "password"
    passwords = [random_password.this.result]
  }

  tags = {
    Name = var.user_name
  }
}

resource "aws_memorydb_acl" "this" {
  name       = var.name
  user_names = [aws_memorydb_user.this.id]

  tags = {
    Name = var.name
  }
}

resource "aws_memorydb_cluster" "this" {
  name        = var.name
  description = var.description

  engine         = "redis"
  engine_version = var.engine_version
  node_type      = var.node_type
  port           = 6379

  num_shards             = var.num_shards
  num_replicas_per_shard = var.num_replicas_per_shard

  acl_name                   = aws_memorydb_acl.this.id
  subnet_group_name          = aws_memorydb_subnet_group.this.id
  security_group_ids         = [aws_security_group.this.id]
  tls_enabled                = true
  kms_key_arn                = aws_kms_key.this.arn
  auto_minor_version_upgrade = true

  snapshot_retention_limit = var.snapshot_retention_days
  maintenance_window       = "sun:18:00-sun:19:00" # 02:00-03:00 SGT

  tags = {
    Name = var.name
  }
}
